### ISSUE TITLE
debugger with node-inspector

### ISSUE THREAD

**Issue by mccarvell** [patrick-steele-idem/browser-refresh#12]
I am not able to get debugging working with browser-refresh. In comparison, these steps work with nodemon:

terminal1: nodemon --debug server.js
terminal2: node-inspector (provides a URL and I'm off an running and debugging breaks trigger)

With browser-refresh I've tried:
terminal1: browser-refresh server.js --debug
terminal2: node-inspector (gives a URL but break points don't seem to do anything and it behaves differently).

Thanks for any help!

**Comment by epinapala** [comment]
+1
