### ISSUE TITLE
Drupal CMS integration

### ISSUE THREAD

**Issue by jurgenhaas** [patrick-steele-idem/browser-refresh#21]
This is just a heads up to let you know that I have just released a [Drupal](https://www.drupal.org) module to easily integrate browser-refresh with this popular CMS so that developers have a very easy way to utilise your great node module. You can fine it at https://www.drupal.org/project/browser_refresh and I'd be happy if you wanted to mention it in your README here on GitHub.

I'll also publish a blog post shortly, anything you want me to mention there?

**Comment by patrick-steele-idem** [comment]
Sorry for the delayed response...super busy these past few days. Just now had a chance to take a look... Nice work!

I don't use Drupal so I haven't tried out your project, but to minimize the number of setup tests, you might want to consider lazily installing the `browser-refresh` and `browser-refresh-client` packages. Also, I would try to avoid a global install of those packages if possible. This would simplify the installation steps since the developer would only need to install Node.js as a prerequisite.

> I'll also publish a blog post shortly, anything you want me to mention there?

In case you want to mention it, `browser-refresh` was created at eBay and we have lots of developers using `browser-refresh`. Therefore, it has been tested by lots of developers and we are continuing to maintain and improve the project.


Thanks for sharing. Glad you were able to find a good use for this project! 

(closing the issue, but feel free to discuss here)

**Comment by jurgenhaas** [comment]
Great Patrick, thanks for your feedback.

What do you mean by "lazily installing `browser-refresh` and `browser-refresh-client`"?

Whether the modules get installed locally or globally doesn't matter that much, I just demonstrated the global way as most developers are working with many different Drupal installations on their dev PC, i.e. for each project a separate Drupal code base. And for those, when they have installed the modules globally they only have to do that once and can make use of them everywhere.

Great news about the background and the origin of the module. Very good to know ad I will certainly mention that in the blog.

**Comment by patrick-steele-idem** [comment]
> What do you mean by "lazily installing browser-refresh and browser-refresh-client"?

When your plugin starts up you can check to see if `browser-refresh` and `browser-refresh-client` have been installed. If those dependencies are missing then you can lazily install them. The next time your plugin starts up those dependencies will be found so startup will be fast.

> Whether the modules get installed locally or globally doesn't matter that much, I just demonstrated the global way as most developers are working with many different Drupal installations on their dev PC, i.e. for each project a separate Drupal code base. And for those, when they have installed the modules globally they only have to do that once and can make use of them everywhere.

Globals have lots of problems. You run into issues with `sudo` and your package doesn't control the versions of its dependencies. Hypothetically, the developer could globally installed a new version of `browser-refresh` that is not compatible with your Drupal plugin. For these reasons, it's much better to install your dependencies locally to your Drupal plugin.

**Comment by jurgenhaas** [comment]
Well, Drupal is a PHP application that runs inside a web server context, i.e. Apache or Nginx. Most likely the use of those processes does not have sufficient permissions to install anything during runtime. That's why that needs to be done explicitly from the console.

Thanks for the heads-up on globals. That makes sense, on the other hand my Drupal module also isn't a node package but a PHP module and therefore the impact might not be that critical. But I keep that in mind.

**Comment by patrick-steele-idem** [comment]
> Well, Drupal is a PHP application that runs inside a web server context, i.e. Apache or Nginx. Most likely the use of those processes does not have sufficient permissions to install anything during runtime. That's why that needs to be done explicitly from the console.

Doing a local install of an npm module should not require any special permissions as long as you have a directory you can write to (which may not be the case).

What you have will obviously work so not a huge deal. I look forward to seeing the blog post.

**Comment by jurgenhaas** [comment]
Yes, it's only about write permissions. In a safe environment the PHP process inside Apache should not have write permissions into the code base, however on a dev environment that might be different. But this way it always works.

If a user is going to use my module and the dependencies are not installed, I throw a warning together with a hint on how to install the node modules. However, as that happens through a CLI command as well, it is likely that the context has enough permissions to do the install. I might be able to do a silent install then, or at least give it a try and only do the warning if that failed. Thanks for nagging on this, that might be a great improvement.
