### ISSUE TITLE
Is there a way to get this working with node-debug

### ISSUE THREAD

**Issue by epinapala** [patrick-steele-idem/browser-refresh#24]
I am looking to start a debug session along with browser-refresh, is it possible?

**Comment by patrick-steele-idem** [comment]
This has come up before and it is not currently supported.I don't think debugging and `browser-refresh` make a lot of sense since `browser-refresh` will restart the process when a JavaScript file is modified. Maybe it would still be helpful?

**Comment by epinapala** [comment]
Doesn't make sense - yes/no :) 

"no" - The problem is that , now, for debugging server side code, we use node-debug, and while we are debugging, we inspect parts of code , we don't make any changes to code. But when we decide to make changes, we had to stop the server and start again in debug mode. having debug + refresh in one thing will make it easier. We will be able to debug > make  changes > debug -> repeat. :)
