### ISSUE TITLE
excessive refreshes when using SourceTree

### ISSUE THREAD

**Issue by yomed** [patrick-steele-idem/browser-refresh#27]
I have `browser-refresh` running. Whenever I tab to SourceTree (viewing commit history), it seems to trigger a file refresh for any file in that diff. Additionally, clicking around to view different parts of the commit history will trigger refreshes similarly. I'm not sure if this is a bug with SourceTree (what are they doing to the files?), but I can see that `watcher.on('modified')` is emitting a `change` event for each file.

**Comment by yomed** [comment]
Closing - looks like it's not connect to SourceTree. Will open a new issue if I can figure out what's going on.

**Comment by lexjacobs** [comment]
@yomed or anybody else that runs into this problem: you have to ignore the .git directory which gets updated every time you add notes to a committed message when using SourceTree. More info on how to ignore a directory: https://www.npmjs.com/package/browser-refresh#overview
