### ISSUE TITLE
Using iojs instead of node

### ISSUE THREAD

**Issue by Solido** [patrick-steele-idem/browser-refresh#3]
I understand that Browser-refresh exec replace the command line and defer to node.
Is it possible to use iojs instead without having to rename it to node ?
a config where I can set the exec name.

Thank you.

**Comment by patrick-steele-idem** [comment]
There are a few small challenges:

1. The `browser-refresh` executable script is hard code to launch with node via the following line: https://github.com/patrick-steele-idem/browser-refresh/blob/76291efe4402837e808d25644806241e0ef0f88a/bin/browser-refresh#L1
2. The `browser-refresh` module uses [`require('child_process').fork`](http://nodejs.org/api/child_process.html#child_process_child_process_fork_modulepath_args_options) which spawns the child process using the same Node.js runtime engine

I think an acceptable solution would be to register a `browser-refresh-iojs` script in addition to the [existing `browser-refresh` script](https://github.com/patrick-steele-idem/browser-refresh/blob/76291efe4402837e808d25644806241e0ef0f88a/package.json#L25).

Then, you can alias `browser-refresh-iojs` to `browser-refresh` or something else in your environment.

Pull Request welcome :)

**Comment by mlrawlings** [comment]
@patrick-steele-idem I think this can be closed since `iojs` has been reconciled with `node`.
