### ISSUE TITLE
Server restart opens up new window when previous windows exist

### ISSUE THREAD

**Issue by basickarl** [patrick-steele-idem/browser-refresh#37]
This bit of code opens up a new window when the server starts up:
```
  if (process.send) {
    process.send({ event: 'online', url: 'http://localhost:3131/' });
  }
```
When I change my code, it restarts (as it should). However it does not use the window which was opened when the server initially started up. So every time I make an adjustment the server restarts and a new window in my browser is opened. This results in quite a few windows being opened and consuming system resources.

Is this expected behavior? If so, how does one use the `process.send('online');` instead when the initial window has been started via `process.send({ event: 'online', url: 'http://localhost:3131/' });`?

**Comment by mlrawlings** [comment]
New version published with fix (`browser-refresh@1.7.1`)
