### ISSUE TITLE
.browser-refresh-ignore does not seem to honor overrides

### ISSUE THREAD

**Issue by seangates** [patrick-steele-idem/browser-refresh#5]
.browser-refresh-ignore does not seem to honor overrides. For example

```
!/node_modules/my-module
```

... does not currently work.

**Note:** I'm not sure if having the "my-module" as a symbolic link matters or not, but my module *is* a symbolic link.

**Comment by patrick-steele-idem** [comment]
The problem is that chokidar won't watch a directory below an ignored directory, but fortunately there is a simple workaround. Add a file named `.browser-refresh` in the root of your project with the following content:

```json
{
    "watch": [
        ".",
        "./node_modules/my-module"
    ]
}
```

Let me know if that does or does not work for you.

**Comment by seangates** [comment]
Didn't work. I now get an error from chokidar. Thanks for continuing to look into it.

**Comment by seangates** [comment]
This worked along with your update. Thanks!
