### ISSUE TITLE
the web page does not refresh

### ISSUE THREAD

**Issue by shirlyLoveU** [patrick-steele-idem/browser-refresh#8]
In my node application, I use jade template, and when some file changed the terminal will log 'Refresh triggered', bug what I see is the web page does not refresh actually. I do not know why

**Comment by leonli** [comment]
你需要使用browser-refresh-client插件来协同工作.

样例代码: https://github.com/lasso-js/lasso/blob/master/browser-refresh/index.js

**Comment by patrick-steele-idem** [comment]
I'm going to go ahead and close this issue because there are not enough details to determine if this is an issue with browser-refresh or how it is being used. Please reopen or open a new Github issue if you are still not able to get browser-refresh working. Thanks!
