### ISSUE TITLE
where to place 'BROWSER_REFRESH_URL'?

### ISSUE THREAD

**Issue by shirlyLoveU** [patrick-steele-idem/browser-refresh#9]
Not using Marko or Dust?
When browser-refresh launches your app a new BROWSER_REFRESH_URL environment variable is added with the URL that should be used to include the client-side script. The value of BROWSER_REFRESH_URL will be similar to http://localhost:12345/browser-refresh.js (the port is random). You should include this library using code similar to the following:

'<script src="{BROWSER_REFRESH_URL}"></script>'

why I can not get the 'BROWSER_REFRESH_URL'

**Comment by patrick-steele-idem** [comment]
When you launch your app there will be an environment variable that contains the URL to include the browser-refresh client-side script code. For example:

```javascript
console.log(process.env.BROWSER_REFRESH_URL)
```

You would need to pass the value of that environment variable to your page-level template and just render it inside a `<script>` tag before the ending `<body>` tag.

Let me know if that doesn't solve your problem.

**Comment by shirlyLoveU** [comment]
that works. Thank you.

**Comment by patrick-steele-idem** [comment]
Glad that worked. You're welcome.
